name: output
description: "output package project"
version: 1.0.1
homepage:
repository: https://github.com/dart-pkg/output

environment:
  sdk: ^3.7.2

dependencies:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
