name: output
description: output package project
version: 1.0.2
homepage:
repository: https://github.com/dart-pkg/output

environment:
  sdk: ^3.7.2

dependencies:

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
  embed: ^1.4.1
  build_runner: ^2.4.15
