name: "output"
description: "output project"
version: "1.0.7"
homepage: null
repository: "https://github.com/dart-pkg/output"
environment:
  sdk: "^3.7.2"
dependencies:
  text_serializer: ^2025.423.1447
dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
